name: 'Broken-Links-Crawler'
description: 'Checks a webiste for broken links'
branding:
  color: red
  icon: check-circle
inputs:
  website_url:  # id of input
    description: 'Which websites to check'
    required: true
  include_url_prefix:
    description: 'Comma separated list of URL prefixes to include'
    required: false
    default: ''
  exclude_url_prefix:
    description: 'Comma separated list of URL prefixes to ignore'
    required: false
    default: 'mailto:,tel:'
  include_url_suffix:
    description: 'Comma separated list of URL suffixes to include'
    required: false
    default: ''
  exclude_url_suffix:
    description: 'Comma separated list of URL suffixes to ignore'
    required: false
    default: ''
  include_url_contained:
    description: 'Comma separated list of URL substrings to include'
    required: false
    default: ''
  exclude_url_contained:
    description: 'Comma separated list of URL substrings to ignore'
    required: false
    default: ''
  web_agent_string:
    description: 'The string to use for the web agent when crawling pages.'
    required: false
    default: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Safari/537.36'
  verbose:
    description: 'Set logging verbosity level: true/false/yes/no/on/off/debug/info/warning/error/critical'
    required: false
    default: 'false'
  max_retry_time:
    description: 'Maximum time for request retries'
    required: false
    default: 30
  max_retries:
    description: 'Maximum request retry count'
    required: false
    default: 4
  max_depth:
    description: 'Maximum site depth level'
    required: false
    default: -1
  always_get_onsite:
    description: 'Always use GET requests for onsite urls'
    required: false
    default: 'false'
  connect_limit_per_host:
    description: 'Limit number of tcp connections per host'
    required: false
    default: '10'
  timeout:
    description: 'Number of seconds to wait for a request to complete'
    required: false
    default: '60'
  search_attrs:
    description: 'Names of element attributes to extract links from'
    required: false
    default: 'href,src'
  resolve_before_filtering:
    description: 'Enables absolute link resolution before applying filtering patterns'
    required: false
    default: 'false'
runs:
  using: 'docker'
  image: 'Dockerfile'
  # args:
    # don't put args here, python will read them from env
